### ISSUE TITLE
toeplitz_calc.py gives wrong hash value for  IP packets

### ISSUE THREAD

**Issue by JasonJiang-VM** [amzn/amzn-ec2-ena-utilities#1]
I did some testing for the hash of IP packets. I uses a IPSEC tunnel to transmit packets:
Local IP: 10.100.0.40
Remote IP: 10.100.0.36
-bash-4.2$ ./toeplitz_calc.py -t 10.100.0.40 -T 0 -r 10.100.0.36 -R 0
Sending traffic from 10.100.0.40:0 to 10.100.0.36:0
to an instance with a default RSS key that cannot be changed

Should result in the hash for all drivers: 0xa7b0a7b (RSS table entry : 123)
-bash-4.2$ ./toeplitz_calc.py -t 10.100.0.36 -T 0 -r 10.100.0.40 -R 0
Sending traffic from 10.100.0.36:0 to 10.100.0.40:0
to an instance with a default RSS key that cannot be changed

Should result in the hash for all drivers: 0xa7b0a7b (RSS table entry : 123)
From rss table, the queue is:
index=123, queue=3
So on both side, it should use queue https://github.com/amzn/amzn-drivers/issues/3 to receive packets. But per my testing, is is queue https://github.com/amzn/amzn-drivers/issues/1 on one side, queue #0 on the other side.
And I use another IP pairs, it showed the same result, the toeplitz_calc.py give one results for this IP pair, but the receive queues are different on both side, one is queue#2, the other is queue#0.
-bash-4.2$ ./toeplitz_calc.py -t 10.100.0.42 -T 0 -r 10.100.0.41 -R 0
Sending traffic from 10.100.0.42:0 to 10.100.0.41:0
to an instance with a default RSS key that cannot be changed

Should result in the hash for all drivers: 0x10f110f1 (RSS table entry : 113)
index=113, queue=1

So here is question, for a IP packet, how ENA driver does the hash? Any comments are appreciated.
Thanks
Jason

**Comment by ShayAgros** [comment]
Hi,

I'm assuming you're using IPsec in transport mode (no gateways are used), please correct me if I'm wrong.

I haven't brought up ipsec traffic yet but I tested with ICMP traffic where the source/dest ports aren't available, and saw that the RX queues on both ends correspond to the script's output when specifying `-R` and `-T` arguments as 0 (similar to what you did).

Is the the transport layer payload encrypted ? Do you mind posting the `tcpdump` output on the receiving side ? e.g. with
```
sudo tcpdump -c 4 -xnni [receiving interface] 'inbound and icmp'
```

**Comment by JasonJiang-VM** [comment]
Hi ShayAgros,
Thanks for response. Yes, I'm using the IPSEC in transport mode. I'm using the DPDK ena driver 2.0.2 version. Even with ping ICMP packets, I found the result is different with what toeplitz_calc.py got:
-bash-4.2$ ./toeplitz_calc.py -r 10.100.0.27 -R 0 -t 10.100.0.74 -T 0
Sending traffic from 10.100.0.74:0 to 10.100.0.27:0
to an instance with a default RSS key that cannot be changed

Should result in the hash for all drivers:              0x760076 (RSS table entry : 118)
index=118, queue=2
But I pinged 20 packets two times, on both side, the packets were received at queue1 instead of queue 2:
RX_Q1_BYTES       : 3920
RX_Q1_CNT         : 40

RX_Q1_BYTES       : 3822
RX_Q1_CNT         : 39

Mightbe you need to change your IP addresses to test it again. 

Thanks
Jason

**Comment by ShayAgros** [comment]
When you say you test it with ping, do you mean the 'ping' program that comes by default with Linux distributions ? Or do you mean some DPDK version of it ?

What instance sizes do you use ?

**Comment by JasonJiang-VM** [comment]
Yes, the ping comes by default with Ubuntu. Here is my topology:

  Ubuntu client(c5n.4xlarge) ------ Gateway(c5n.4xlarge)  -------VPN tunnel ---------- Gateway(c5n.4xlarge) ------- Ubuntu client(c5n.4xlarge)

They are all go through the ena, on ubuntu, it is ena linux driver, on gateway, it is ena DPDK 2.0.2 version driver.  No matter I monitor the Gateway receiving from ubuntu client  or Gateway receiving from VPN tunnel, it is not the one getting from the hash script. 

So I would like to know by design, how a DPDK 2.0.2 driver programs the HW to receive the IP packets. And that doesn't list in the readme document or anywhere else. Please let me know if you need more input.

Thanks
Jason

**Comment by ShayAgros** [comment]
ENA HW allows to modify RSS key for instances of gen 5 or newer (e.g. c5n.*, m5n.* etc. and c6gn.*, c6in.* etc.). The addition of the `-k` argument to the toeplitz script "tells it" whether the instance is of gen4 or of gen5 and newer.

In addition, to be able to query and set the RSS key a new enough driver is required. If you use c5n.4xlarge with the default Linux driver, it very likely has a new enough driver and you can use
```
ethtool -x eth1
```
and pass the value of `RSS hash key:` to the script as `-k` argument. E.g. to get the RX queue of ping between `172.31.52.165` to `172.31.52.143`
```
toeplitz_calc.py -t 172.31.52.165 -T 0 -r 172.31.52.143 -R 0 -k 07:59:95:5a:3f:e0:cf:f0:b5:2f:cd:66:9f:3d:e5:11:8b:a6:c4:54:08:d3:48:49:73:cb:e2:56:43:fa:4c:ad:f1:6e:9d:d2:df:6d:d1:5e
```

In the DPDK driver you're using (DPDK 2.0.2) the support for querying and modifying the RSS key isn't implemented so you're not able to find out which key is used. Nevertheless, you still need to pass a key to the `toeplitz_calc.py` script so that it would calculate the hash for gen5 (like your c5n.4xlarge) and not for gen4).

So you have two options here:
1. Update your DPDK driver. Version 2.4.0 has the option to query and set Toeplitz RSS key. If you decide to upgrade, you can query the key and pass it to the script to get the correct hash (and receive queue) similar to the example above
2. If you prefer to stay with the current one, you can pass the script the RSS key which is the default value stored in the ENA HW (you can find it in the script's code itself). The key is
```
be:ac:01:fa:6a:42:b7:3b:80:30:f2:0c:77:cb:2d:a3:ae:7b:30:b4:d0:ca:2b:cb:43:a3:8f:b0:41:67:25:3d:25:5b:0e:c2:6d:5a:56:da
```
for *all* gen6 instances with a driver that *doesn't support modifying it* (drivers that do override this value when loaded).
e.g. for ping traffic
```
toaplitz_calc.py -t [client ip] -T 0 -r [server ip] -R 0 -k be:ac:01:fa:6a:42:b7:3b:80:30:f2:0c:77:cb:2d:a3:ae:7b:30:b4:d0:ca:2b:cb:43:a3:8f:b0:41:67:25:3d:25:5b:0e:c2:6d:5a:56:da
```

**Comment by JasonJiang-VM** [comment]
Thanks ShayAgros.  I verified with what you provided above,  the results match what the script gave.

**Comment by davidarinzon** [comment]
Hi @JasonJiang-VM 
Do you have any further questions?

**Comment by JasonJiang-VM** [comment]
Thanks David and all. I don't have any other questions. It can be closed. 

Jason
